#!/usr/bin/env bash
function eval_timetracking {
  perl -ne 'BEGIN {%s=()} @a=split(";");$x=$a[4];$x=~s/,/./g;if($x == 0 || $a[6] eq "") {next};$s{$a[6]}+=$x; END {foreach $k(keys %s){printf "%12s: %.2f\n", $k, $s{$k}}}'
}

function prolog {
  file="$1"
  if [[ -z "$file" ]]; then
    line=$(head -n 1 "$file")
  fi
  if [[ "$line" =~ %.gprolog ]]; then
    gprolog --consult-file "$file"
  elif [[ "$line" =~ %.bp ]]; then
    bp -g "['$file']"
  else
    swipl -f "'$file'"
  fi
}

function forget_host {
  sed -i .old "$1d" ~/.ssh/known_hosts
}

function racoonupdate {
  sudo sed -i.old "s/local_address .*;/local_address $(ifconfig en0 | grep 'inet ' | cut -d ' ' -f 2);/" /etc/racoon/213.198.82.174.conf
}

### n for node version management
function load-node-version {
  if [[ -f .node-version ]]; then
    n $(cat .node-version)
  fi
}
function cd {
  builtin cd "$@";
  "load-node-version";
}

function devinfo {
  echo "which ruby:     " $(which ruby)
  echo "  ruby version: " $(ruby -v)
  echo "  rails version:" $(rails -v)
  echo
  echo "which node:     " $(which node)
  echo "  node version: " $(node -v)
}

function path {
  ruby -e 'require "pp"; pp ENV["PATH"].split(":")'
}
