#!/usr/bin/env bash
export PATH=$HOME/.pyenv/shims:$PATH
export PYENV_SHELL=bash
source '/usr/local/Cellar/pyenv/1.2.7/libexec/../completions/pyenv.bash'
command pyenv rehash 2>/dev/null
pyenv() {
  local command
  command="${1:-}"
  if [ "$#" -gt 0 ]; then
    shift
  fi

  case "$command" in
  rehash|shell)
    eval "$(pyenv "sh-$command" "$@")";;
  *)
    command pyenv "$command" "$@";;
  esac
}
